-- MySQL Script generated by MySQL Workbench
-- Thu Jan 28 16:00:20 2021
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema SWAPI
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema SWAPI
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `SWAPI` DEFAULT CHARACTER SET utf8 ;
USE `SWAPI` ;

-- -----------------------------------------------------
-- Table `SWAPI`.`Users`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `SWAPI`.`Users` ;

CREATE TABLE IF NOT EXISTS `SWAPI`.`Users` (
                                               `UserId` INT NOT NULL AUTO_INCREMENT,
                                               `Email` LONGTEXT NOT NULL,
                                               `Pass` LONGTEXT NOT NULL,
                                               `RegistrationTime` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
                                               PRIMARY KEY (`UserId`))
    ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `SWAPI`.`HeroAssignments`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `SWAPI`.`HeroAssignments` ;

CREATE TABLE IF NOT EXISTS `SWAPI`.`HeroAssignments` (
                                                         `UserId` INT NOT NULL,
                                                         `HeroId` INT NOT NULL,
                                                         PRIMARY KEY (`UserId`),
    UNIQUE INDEX `UserId_UNIQUE` (`UserId` ASC) VISIBLE,
    CONSTRAINT `fk_HeroesAssignment_Users`
    FOREIGN KEY (`UserId`)
    REFERENCES `SWAPI`.`Users` (`UserId`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
    ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
